# Generated by Django 5.1.5 on 2025-01-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available ', 'Availble'), ('not_available', 'Not Avaiable')], default='available', max_length=60, verbose_name='Status'),
        ),
    ]
