# Generated by Django 5.1.5 on 2025-01-29 17:01

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_image_alter_product_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default=builtins.print, max_length=255, verbose_name='Product Brand'),
            preserve_default=False,
        ),
    ]
